[package]
name = "ffmpeg_cli_utils"
version = "0.1.0"
edition = "2021"
authors = ["Tonywho <hujingyuan25@163.com>"]

[dependencies]
futures = "0.3.26"
tokio = { version = "1", features = ["full"] }

[features]
default = ["async"]
async = []
